# Generated by Django 4.2.10 on 2025-05-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={},
        ),
        migrations.RemoveField(
            model_name="token",
            name="is_active",
        ),
        migrations.AddField(
            model_name="token",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="token",
            name="parent_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_tokens",
                to="authentication.token",
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[("access", "Access Token"), ("refresh", "Refresh Token")],
                default="access",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.TextField(unique=True),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["user", "token_type"], name="auth_tokens_user_id_6e4d12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["expires_at"], name="auth_tokens_expires_f09206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["is_blacklisted"], name="auth_tokens_is_blac_3a309f_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="token",
            table="auth_tokens",
        ),
    ]
