version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vvv_database
      POSTGRES_USER: vvv_user
      POSTGRES_PASSWORD: vvv_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./env/backend.env
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.prod
    depends_on:
      - postgres
      - redis
    ports:
      - "8001:8000"

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A api worker -l info
    env_file:
      - ./env/backend.env
    depends_on:
      - backend
      - redis

  beat:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A api beat -l info
    env_file:
      - ./env/backend.env
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    env_file:
      - ./env/frontend.env
    ports:
      - "3001:3001"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
  redis_data:
