version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vvv_database
      POSTGRES_USER: vvv_user
      POSTGRES_PASSWORD: vvv_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vvv_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vvv_network

volumes:
  postgres_data:
  redis_data:

networks:
  vvv_network:
    driver: bridge 