# Generated by Django 4.2.21 on 2025-08-03 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_account_account_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pipelines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataqualitycheck",
            name="data_source",
        ),
        migrations.RemoveField(
            model_name="pipelinejob",
            name="data_source",
        ),
        migrations.RemoveField(
            model_name="pipelinelog",
            name="data_source",
        ),
        migrations.AlterField(
            model_name="pipelinejob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("sync", "Data Sync"),
                    ("import", "Data Import"),
                    ("transform", "Data Transform"),
                    ("export", "Data Export"),
                    ("backfill", "Historical Backfill"),
                ],
                default="sync",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DataPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Pipeline name (e.g., 'Porsa Orders Sync')",
                        max_length=255,
                    ),
                ),
                (
                    "pipeline_type",
                    models.CharField(
                        choices=[
                            ("woocommerce", "WooCommerce"),
                            ("google_search_console", "Google Search Console"),
                            ("google_ads", "Google Ads"),
                            ("google_analytics", "Google Analytics"),
                            ("facebook_ads", "Facebook Ads"),
                            ("tiktok_ads", "TikTok Ads"),
                            ("linkedin_ads", "LinkedIn Ads"),
                            ("shopify", "Shopify"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Only"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "schedule_config",
                    models.JSONField(
                        default=dict,
                        help_text="Schedule-specific configuration (e.g., time, day of week)",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Pipeline-specific configuration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipelines",
                        to="users.account",
                    ),
                ),
                (
                    "account_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipelines",
                        to="users.accountconfiguration",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pipeline_data_pipelines",
                "ordering": ["-created_at"],
                "unique_together": {("account", "pipeline_type", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="pipelineanalytics",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dataqualitycheck",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pipelines.datapipeline",
            ),
        ),
        migrations.AddField(
            model_name="pipelineanalytics",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pipelines.datapipeline",
            ),
        ),
        migrations.AddField(
            model_name="pipelinejob",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="pipelines.datapipeline",
            ),
        ),
        migrations.AddField(
            model_name="pipelinelog",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pipelines.datapipeline",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pipelineanalytics",
            unique_together={("pipeline", "date")},
        ),
        migrations.RemoveField(
            model_name="pipelineanalytics",
            name="data_source",
        ),
        migrations.DeleteModel(
            name="DataSource",
        ),
    ]
