import Head from "next/head";
import Footer from "../components/footer/Footer";
import Nav from "../components/Nav/Nav";
import Hero from "../components/HeroSection/Hero";
import Services from "../components/Services/Services";
import Prices from "../components/Prices/Prices";
import CustomerCases from "../components/CustomerCases/CustomerCases";
import AboutMe from "../components/AboutMe/AboutMe";
import { LinkingModel } from "../components/model/LinkModel";

const Links: LinkingModel[] = [
  new LinkingModel("1", "Services", "#services"),
  new LinkingModel("2", "Om os", "#about"),
  new LinkingModel("3", "Cases", "#cases"),
  new LinkingModel("4", "Priser", "#prices"),
  new LinkingModel("5", "Kontakt", "#contact"),
  new LinkingModel("6", "Login", "/login"), // Note: This uses a full path, not a hash
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Veveve</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav links={Links} />
      <Hero 
        title="Internet på jysk" 
        subtitle="[veh-VEH-veh]"
      />
      <Services />
      <AboutMe />
      <CustomerCases />
      <Prices />
      <Footer />
    </>
  );
}
