# Generated by Django 4.2.10 on 2025-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Regular User"),
                    ("company_admin", "Company Administrator"),
                    ("admin", "System Administrator"),
                ],
                default="user",
                max_length=50,
            ),
        ),
    ]
