# Generated by Django 4.2.21 on 2025-07-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_agency_alter_user_company_alter_user_role_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_all_companies",
            field=models.BooleanField(
                default=True,
                help_text="If True, user has access to all companies in their agency",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="accessible_companies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Companies this user has access to when access_all_companies is False",
                related_name="accessible_users",
                to="users.company",
            ),
        ),
    ]
