# Generated by Django 4.2.21 on 2025-08-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_access_all_companies_user_accessible_companies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("google_ads", "Google Ads"),
                    ("facebook_ads", "Facebook Ads"),
                    ("linkedin_ads", "LinkedIn Ads"),
                    ("tiktok_ads", "TikTok Ads"),
                    ("google_analytics", "Google Analytics"),
                    ("google_search_console", "Google Search Console"),
                    ("woocommerce", "WooCommerce"),
                    ("shopify", "Shopify"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AccountConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_data",
                    models.JSONField(
                        default=dict,
                        help_text="Stores configuration data like API keys, URLs, etc.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="users.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Configuration",
                "verbose_name_plural": "Account Configurations",
            },
        ),
    ]
