# Generated by Django 4.2.21 on 2025-08-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_account_account_type_accountconfiguration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="account_id",
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_type",
        ),
        migrations.AddField(
            model_name="account",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of this account"
            ),
        ),
        migrations.AddField(
            model_name="accountconfiguration",
            name="config_type",
            field=models.CharField(
                choices=[
                    ("woocommerce", "WooCommerce"),
                    ("google_ads", "Google Ads"),
                    ("google_analytics", "Google Analytics"),
                    ("google_search_console", "Google Search Console"),
                    ("facebook_ads", "Facebook Ads"),
                    ("linkedin_ads", "LinkedIn Ads"),
                    ("tiktok_ads", "TikTok Ads"),
                    ("shopify", "Shopify"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="accountconfiguration",
            name="name",
            field=models.CharField(
                default="Default Configuration",
                help_text="Name for this configuration (e.g., 'Main Store', 'Ads Account')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="accountconfiguration",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="users.account",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountconfiguration",
            unique_together={("account", "config_type", "name")},
        ),
    ]
