# Generated by Django 4.2.21 on 2025-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_account_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="currency_code",
            field=models.CharField(
                default="USD",
                help_text="ISO 4217 code, e.g., USD, EUR, DKK",
                max_length=3,
            ),
        ),
    ]
