# Generated by Django 4.2.21 on 2025-08-01 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WooCommerceClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("base_url", models.URLField()),
                ("consumer_key", models.CharField(max_length=255)),
                ("consumer_secret", models.CharField(max_length=255)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "woocommerce_clients",
            },
        ),
        migrations.CreateModel(
            name="WooCommerceJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("daily_sync", "Daily Sync"),
                            ("historical_backfill", "Historical Backfill"),
                            ("manual_sync", "Manual Sync"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("orders_processed", models.IntegerField(default=0)),
                ("orders_created", models.IntegerField(default=0)),
                ("orders_updated", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="woocommerce.woocommerceclient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "woocommerce_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WooCommerceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50)),
                ("order_number", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("customer_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "customer_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("billing_address", models.JSONField(default=dict)),
                ("shipping_address", models.JSONField(default=dict)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_method_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_created", models.DateTimeField()),
                ("date_modified", models.DateTimeField()),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="woocommerce.woocommerceclient",
                    ),
                ),
            ],
            options={
                "db_table": "woocommerce_orders",
            },
        ),
        migrations.CreateModel(
            name="WooCommerceSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DEBUG", "Debug"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="woocommerce.woocommerceclient",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="woocommerce.woocommercejob",
                    ),
                ),
            ],
            options={
                "db_table": "woocommerce_sync_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WooCommerceOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=50)),
                ("product_name", models.CharField(max_length=255)),
                (
                    "product_sku",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_class", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("meta_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="woocommerce.woocommerceorder",
                    ),
                ),
            ],
            options={
                "db_table": "woocommerce_order_items",
            },
        ),
        migrations.AddIndex(
            model_name="woocommerceorder",
            index=models.Index(
                fields=["client", "date_created"], name="woocommerce_client__18a557_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="woocommerceorder",
            index=models.Index(fields=["status"], name="woocommerce_status_67c9f0_idx"),
        ),
        migrations.AddIndex(
            model_name="woocommerceorder",
            index=models.Index(
                fields=["customer_email"], name="woocommerce_custome_8784b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="woocommerceorder",
            unique_together={("client", "order_id")},
        ),
    ]
