# Generated by Django 4.2.21 on 2025-08-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("woocommerce", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="woocommerceorder",
            name="woocommerce_client__18a557_idx",
        ),
        migrations.AlterUniqueTogether(
            name="woocommerceorder",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="woocommercejob",
            name="client",
        ),
        migrations.RemoveField(
            model_name="woocommercesynclog",
            name="client",
        ),
        migrations.AddField(
            model_name="woocommercejob",
            name="client_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="woocommerceorder",
            name="client_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="woocommercesynclog",
            name="client_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="woocommerceorder",
            unique_together={("client_name", "order_id")},
        ),
        migrations.AddIndex(
            model_name="woocommerceorder",
            index=models.Index(
                fields=["client_name", "date_created"],
                name="woocommerce_client__4d95ab_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="woocommerceorder",
            name="client",
        ),
        migrations.DeleteModel(
            name="WooCommerceClient",
        ),
    ]
