# Generated by Django 4.2.21 on 2025-08-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "woocommerce",
            "0002_remove_woocommerceorder_woocommerce_client__18a557_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Traffic source (e.g., google, (direct), fb)",
                        max_length=255,
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        help_text="Traffic medium (e.g., organic, utm, referral)",
                        max_length=255,
                    ),
                ),
                (
                    "source_medium",
                    models.CharField(
                        help_text="Combined source/medium (e.g., google/organic)",
                        max_length=255,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="Channel name (e.g., google / organic)",
                        max_length=255,
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("Direct", "Direct"),
                            ("SEO", "SEO"),
                            ("Organic Social", "Organic Social"),
                            ("Email", "Email"),
                            ("Referal", "Referal"),
                            ("ChatGpt", "ChatGpt"),
                            ("Paid Social", "Paid Social"),
                            ("Paid Search", "Paid Search"),
                            ("Organic Search", "Organic Search"),
                            ("Test", "Test"),
                        ],
                        help_text="Channel category",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this classification rule is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Channel Classification",
                "verbose_name_plural": "Channel Classifications",
                "db_table": "woocommerce_channel_classifications",
                "ordering": ["channel_type", "source"],
                "unique_together": {("source", "medium")},
            },
        ),
    ]
