# Generated by Django 4.2.21 on 2025-08-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0002_add_woocommerce_export_fields'),
        ('woocommerce', '0003_channelclassification'),
    ]

    operations = [
    ]
