# Generated by Django 4.2.21 on 2025-09-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("woocommerce", "0004_merge_20250820_1909"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="woocommerceorder",
            name="woocommerce_custome_8784b1_idx",
        ),
        migrations.RemoveIndex(
            model_name="woocommerceorder",
            name="woocommerce_client__4d95ab_idx",
        ),
        migrations.RenameIndex(
            model_name="woocommerceorder",
            new_name="woocommerce_attribu_d6d69b_idx",
            old_name="woocommerce_attribution_utm_source_idx",
        ),
        migrations.RenameIndex(
            model_name="woocommerceorder",
            new_name="woocommerce_order_d_2c1b7d_idx",
            old_name="woocommerce_order_date_idx",
        ),
        migrations.RemoveField(
            model_name="woocommerceorder",
            name="customer_email",
        ),
        migrations.RemoveField(
            model_name="woocommerceorder",
            name="customer_first_name",
        ),
        migrations.RemoveField(
            model_name="woocommerceorder",
            name="customer_last_name",
        ),
        migrations.AddField(
            model_name="woocommerceorder",
            name="billing_email",
            field=models.EmailField(
                blank=True, db_column="customer_email", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="woocommerceorder",
            name="billing_first_name",
            field=models.CharField(
                blank=True, db_column="customer_first_name", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="woocommerceorder",
            name="billing_last_name",
            field=models.CharField(
                blank=True, db_column="customer_last_name", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="woocommerceorder",
            name="is_new_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="woocommerceorder",
            name="currency",
            field=models.CharField(db_column="currency", default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="woocommerceorder",
            name="date_completed",
            field=models.DateTimeField(
                blank=True, db_column="date_completed", null=True
            ),
        ),
        # Avoid altering NOT NULL columns in SQLite table rebuild; keep existing definitions
        migrations.AddIndex(
            model_name="woocommerceorder",
            index=models.Index(
                fields=["client_name", "order_date"],
                name="woocommerce_client__4fcd80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="woocommerceorder",
            index=models.Index(
                fields=["billing_email"], name="woocommerce_custome_8784b1_idx"
            ),
        ),
    ]
